# Default application properties.
# 
# Create an application.yml on your working directory to override these values,
# or application-X.yml where X is the name of the active profile provided via
# the JVM argument -Dspring.profiles.active=X

# Default profile
server:
  port: 8080
  address: "0.0.0.0"
  
spring:
  datasource:
    jmx-enabled: true
    tomcat:
      initialSize: 3
      maxActive: 15
      minIdle: 1
      maxIdle: 2
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: VALUES CURRENT_DATE
      timeBetweenEvictionRunsMillis: 35000
      minEvictableIdleTimeMillis: 55000
      validationInterval: 35000
      removeAbandoned: true
      removeAbandonedTimeout: 600
      jdbcInterceptors: "ConnectionState;StatementCache(prepared=true,callable=false,max=50);ResetAbandonedTimer"
  jmx:
    enabled: true
  mvc:
    formcontent.putfilter.enabled: false
  resources.cache-period: 86400

logging:
  pattern:
    console: "${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file:  "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

debugMode: false

---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/solarnetwork
    username: solarnet
    password: solarnet
    platform: postgresql
    initialize: false

debugMode: true

logging:
  level:
    net.solarnetwork: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
